import Header from "@/components/Header";
import { locales } from "@/i18n/config";
import { Metadata } from "next";
import "../globals.css";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import { ItemsProvider } from "@/context/itemsContext";
import Footer from "@/components/homePage/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const helvetica = localFont({
  src: "../../public/fonts/HelveticaNeueBlack.otf",
  variable: "--font-helvetica-neue",
});

export async function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "Create Next App",
    description: "Generated by create next app",
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pl" className={`${helvetica.variable} font-sans`}>
      <body>
        <Header />
        <ItemsProvider>
          <main>{children}</main>
        </ItemsProvider>
        <div className="overflow-hidden">
          <Footer />
        </div>
      </body>
    </html>
  );
}
